### ISSUE TITLE
Interaction constraints not working

### ISSUE THREAD

**Issue by Chrisjb** [ray-project/lightgbm_ray#41] opened 2023-01-17 17:39 UTC
Hi,

I've been testing using the `interaction_constraints` parameter from lightgbm (see [here](https://lightgbm.readthedocs.io/en/latest/Parameters.html#interaction_constraints)). 

Unfortunately, passing in the list of constraints causes training to fail with a sigsegv error.

Example:
```
#%%
# set up and load boston data
import numpy as np
import pandas as pd
from lightgbm_ray import RayLGBMRegressor, RayParams, RayDMatrix
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import ray
import os

boston = load_boston()
x, y = boston.data, boston.target
df = pd.DataFrame(x, columns= boston.feature_names)

# make into dmatrix
train_df_with_target = df.copy()
train_df_with_target['target'] = y

train_set = RayDMatrix(
    data=train_df_with_target,
    label = 'target'
    )

# set params and ray params
params = {
    'boosting_type': 'goss',
    'objective': 'regression',
    'metric': 'rmse',
    'num_leaves': 10,
    'max_depth': 4,
    'learning_rate': 0.05,
    'verbose': 1
}

ray_params = RayParams(
    num_actors=2,
    cpus_per_actor = 2,
    )



#%% set up constraint (age cannot interact with any other feature)
constrained_feature = 'AGE'
other_features = [x for x,y in enumerate(df.columns) if y != constrained_feature ]
constrained_feature_idx = [x for x,y in enumerate(df.columns) if y == constrained_feature ]

constraint = [constrained_feature_idx, other_features]


#%% fit model
mod_ray_constrained = RayLGBMRegressor(
    random_state=100,
    interaction_constraints = constraint,
    **params
)


mod_ray_constrained.fit(train_set,
    y='target',
    eval_set = [(train_set, 'target')],
    eval_names=["train"],
    ray_params=ray_params)
```

The constrained model fit returns the error:

> (_RemoteRayLightGBMActor pid=266, ip=10.99.13.194) *** SIGSEGV received at time=1673976819 on cpu 3 ***
> (_RemoteRayLightGBMActor pid=266, ip=10.99.13.194) PC: @     0x7fedc74926f7  (unknown)  (unknown)
> (_RemoteRayLightGBMActor pid=266, ip=10.99.13.194)     @     0x7fedc750d420  (unknown)  (unknown)
> (_RemoteRayLightGBMActor pid=266, ip=10.99.13.194) [2023-01-17 09:33:39,994 E 266 292] logging.cc:361: *** SIGSEGV received at time=1673976819 on cpu 3 ***
> (_RemoteRayLightGBMActor pid=266, ip=10.99.13.194) [2023-01-17 09:33:39,994 E 266 292] logging.cc:361: PC: @     0x7fedc74926f7  (unknown)  (unknown)
> (_RemoteRayLightGBMActor pid=266, ip=10.99.13.194) [2023-01-17 09:33:39,994 E 266 292] logging.cc:361:     @     0x7fedc750d420  (unknown)  (unknown)
> (_RemoteRayLightGBMActor pid=266, ip=10.99.13.194) Fatal Python error: Segmentation fault

Running this code with non-distributed `lightgbm` works fine, as does the above code with interaction constraints removed.

**Comment by Yard1** [comment] 2023-01-17 17:57
Thanks, will take a look.

**Comment by Yard1** [comment] 2023-01-20 18:06
@Chrisjb thanks for the report. I can indeed reproduce the issue. However, it looks like it is also present in LightGBM Dask integration, which would hint at it being an issue with LightGBM itself. I'd recommend opening an issue in LightGBM repo and providing context there. You should include the below Dask reproduction script as well:
```python
from distributed import Client, LocalCluster
import dask.dataframe as dd
import pandas as pd
from sklearn.datasets import load_boston
import lightgbm as lgb

if __name__ == "__main__":
    print("loading data")
    boston = load_boston()
    X, y = boston.data, boston.target

    params = {
        'boosting_type': 'goss',
        'objective': 'regression',
        'metric': 'rmse',
        'num_leaves': 10,
        'max_depth': 4,
        'learning_rate': 0.05,
        'verbose': 10
    }

    print("initializing a Dask cluster")

    cluster = LocalCluster()
    client = Client(cluster)

    print("created a Dask LocalCluster")

    print("distributing training data on the Dask cluster")
    df = pd.DataFrame(X, columns=boston.feature_names)
    dX = dd.from_pandas(df, npartitions=4)
    dy = dd.from_pandas(pd.Series(y, name="target"), npartitions=4)

    constrained_feature = 'AGE'
    other_features = [
        x for x, y in enumerate(df.columns) if y != constrained_feature
    ]
    constrained_feature_idx = [
        x for x, y in enumerate(df.columns) if y == constrained_feature
    ]

    constraint = [constrained_feature_idx, other_features]

    print("beginning training")

    dask_model = lgb.DaskLGBMRegressor(
        interaction_constraints=constraint, **params)
    dask_model.fit(dX, dy)
    assert dask_model.fitted_

    print("done training")
```

I'll close this issue as it is not on our side, feel free to reopen if you have any other questions regarding this.

**Closed by Yard1** 2023-01-20 18:06 UTC
